### ISSUE TITLE
/chart staucht graph zusammen

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#1]
Nach Bestätigung durch @Fulgen301, dass das so nicht im Sinne des Entwicklers ist:
/chart staucht alle graphen außer "oc" (was auch immer das ist) zusammen, anstatt sie zu überschreiben. Die anderen graphen sollten sich genau so verhalten, wie der oc-graph, vielleicht etwas langsamer laufen.

**Comment by Fulgen301** [comment]
Alle Graphen verhalten sich exakt gleich - sobald eine gewisse Grenze überschritten wurde, wird nicht mehr der komplette Buffer angezeigt, sondern horizontal mitgescrollt. Bei "oc" alias ObjectCount passiert dies früher, da dieser Wert jeden Frame aktualisiert wird, während dies bei den anderen Graphen nur jede Sekunde passiert.

**Comment by Somebodyisnobody** [comment]
Könnte man diese Grenze etwas hinabsetzen? Meinem Empfinden nach kann man durch diese Stauchung kaum etwas sinnvolles erkennen.
