### ISSUE TITLE
Add a Hotkey for Sound on / off

### ISSUE THREAD

**Issue by Danghorx** [legacyclonk/LegacyClonk#105]
There is no hotkey for sound on / off but for music on / off.

**Comment by maxmitti** [comment]
Any suggestions for which (default) hotkey to use?

Since it is related to music, Ctrl+F3 comes to mind.

**Comment by Danghorx** [comment]
F10-F12 is also free, or it needs a combination with ctrl or alt.

**Comment by Somebodyisnobody** [comment]
Combination with Strg / Alt is my prefered option as the user can just remember "F3 is something with audio"
