### ISSUE TITLE
c4group - Set author

### ISSUE THREAD

**Issue by westnordost** [legacyclonk/LegacyClonk#109]
Is it possible with C4Group to specify the name of the Author the packed C4* file should have? If not, would it be possible to add this feature?

**Reason**:
I am currently compiling an "ultimate clonk collection" which shall include all the best scenarios created by the clonk community over the last 20+ years. See also [this thread](https://forum.clonkspot.org/t/suche-verschollene-szenarien-fuer-grosse-clonk-collection/1510). Now, some scenarios do not have their original author displayed because either they were included in some contest, have been [included in the official game content](https://forum.clonkspot.org/t/suche-verschollene-szenarien-fuer-grosse-clonk-collection/1510/12?u=newton) or they were re-published after making some small fixes (e.g. applies for all the CHP ever did).
So, I'd like to re-pack these things and credit their original author(s) correctly. (One step further, and one might even credit them a additionally with their nicknames, e.g. "David Dormagen (Zapper)" etc.)

**Comment by Fulgen301** [comment]
The command line `c4group` binary doesn't support this feature at the moment - Henry released [c4author](https://ccan.de/cgi-bin/ccan/ccan-view.pl?a=view&i=5384) years ago and the format is unchanged, so it'll still work.

Adding author setting functionality to `c4group` might cause people to pretend they made certain objects, on the other hand, if they can run the binary, they certainly can run `c4author`...

**Comment by Somebodyisnobody** [comment]
Duplicate of #21

**Comment by Fulgen301** [comment]
Good point (I love how my opinion on the subject changed in those two years)

**Comment by Somebodyisnobody** [comment]
?! Closing this issue was not my intention. I still believe that this would be a good option.

**Comment by westnordost** [comment]
Another use case for this is to set the author to a "made up" name instead of the real name of the one who registered the clonk version one is packing that with. E.g. "Hazard-Team", "CMC-Team", "Team #WAZ", "Matthes Bender, Sven Eberhardt"...
(Fun quiz: Do you know the scenario(s) the last two may refer to? )

**Comment by Fulgen301** [comment]
c4group.exe already respects `General.Name`, which can be set via a configuration file, the Windows registry (`Set-ItemProperty -Path "HKCU:\SOFTWARE\LegacyClonk Team\LegacyClonk\General" -Name Name -Value "TheName"`) or the advanced settings dialog that will be part of [359]. Therefore, while it isn't as convenient as a command line argument for c4group.exe, this is already possible, also in a automated fashion by editing the configuration value before launching c4group.exe to unpack and repack the group.

**Comment by westnordost** [comment]
Ah cool, so given there is one alternative and one proper (yet not super convenient) solution, I'll just close this.
