### ISSUE TITLE
Visual: Wrong "let go" command icon when using jump and run controls

### ISSUE THREAD

**Issue by fritzw** [legacyclonk/LegacyClonk#117]
Minor visual issue:

Letting go of an object always shows the "Double Down" icon instead of the "Down" icon, when using jump and run (AutoStop) controls. However, letting go only requires pressing down once for items, like trees. Only items that have their own function on the down button, like the catapult, require "Double Down" to let go.

**Comment by maxmitti** [comment]
I wonder if it is fixable easily enough.
The main question probably is how to know when a Double Down is actually needed for letting go.

At the moment I believe it can only be approximated roughly, because there is no direct sign that a single down is suppressed.

**Comment by fritzw** [comment]
You are right, that would probably require some additional object property, and adjustments to all scripts that have a special use for ControlDown... Probably not worth the effort for a minor visual issue.

But at least now there's a record of it here. If someone wants to tackle this, it can be reopened.
