### ISSUE TITLE
Add #legacyclonk to the defaults

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#19]
Enchanement: Add #legacyclonk to the defaults in the IRC Client

**Comment by maxmitti** [comment]
Before we do this the euIRC admins should agree that we can disable the lockdown of LCs IRC-Client to channel names beginning with #clonk.

**Comment by Somebodyisnobody** [comment]
There is an agreement required? I solved this over the registry value REG_DWORD "AllowAllChannels" = 1 in the key "IRC"

**Comment by maxmitti** [comment]
Long time ago when CR introduced the IRC client, the euIRC admins required to only allow channels beginning with #clonk to avoid flooding all the channels with clonkers. Obviously, this shouldn't be a problem anymore now, but at least we should get their blessing to disable the lockdown.

We know the AllowAllChannels config, but it has always been undocumented and hidden until we made all config values visible by default in LC.

**Comment by maxmitti** [comment]
Ok, we are allowed to remove the limitation.

**Comment by maxmitti** [comment]
But keep in mind that the change in default value only applies on the first start of LC.
