### ISSUE TITLE
c4group add option to change author

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#21]
[c4author](https://ccan.de/cgi-bin/ccan/ccan-view.pl?a=view&i=5384) can change the author of a group. That would be a good feature to implement into g4group after registering was removed.

**Comment by Fulgen301** [comment]
This would allow anyone to claim authorship of any group. It's bad enough that c4author exists, but c4group shouldn't get that functionality, otherwise we can just drop the author field.
