### ISSUE TITLE
Categorize IP packets when ingame

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#24]
LC sends IP packets with default DSCP priority (0000 00). We could set a higher classification for QoS. See https://www.msxfaq.de/netzwerk/qos/qosbandbreiteprio.htm

**Comment by Fulgen301** [comment]
As there's no apparent solution for Windows and Linux users can set it via `iptables` (and it didn't change anything for me), I'm gonna close this for now.
