### ISSUE TITLE
Folder structure under windows

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#25]
LegacyClonk stores user-specific game files and necessary program files in a folder (Program Files x86). This folder requires administrator rights under Windows. Therefore, we should consider using a system that will run the vast majority of available applications: Program files such as dlls, executables or even the official packages are stored in Program Files x86. User specific files like dynamic network resources, external c4 files or the clonk.log are stored in AppData/Roaming/LegacyClonk.

Here are the key data of the proposal:
1.  All non-vanilla files, dynamic network files and logs from Clonk end up in AppData/Roaming/LegacyClonk
2. Vanilla files (System.c4g, Graphics.c4g, legacyclonk/content) and executables or dlls remain in Program Files x86 (those updated by LC c4updater)
3. At startup it is checked whether a (c4d|c4s|c4f) file already exists in AppData/Roaming/LegacyClonk. If not, all non-Vanilla files will be moved (possibly to AppData/Roaming/LegacyClonk/Ressources or ./mods for clarity), or at least copied, if Program Files x86 is missing ReadOnly. The Clonk.log is created directly with startup in AppData/Roaming/LegacyClonk, as are dynamic network files (possibly in AppData/Roaming/LegacyClonk/Network).
4. LC will first search for packets in AppData/Roaming/LegacyClonk. If there is a file with the same name in both directories, AppData/Roaming/LegacyClonk is preferred and Program Files x86 is ignored.
5. There are exceptions to the preferential treatment for vanilla packages. These could either be hardcoded by name (more administration effort) or LC will always check if the package is from the c4author "Legacy Clonk Team" (here less administration effort), or similar techniques to detect official packages.

Ad 4: The goal is to use AppData/Roaming/LegacyClonk. Therefore the files there should also be given preferential treatment. If a required file in AppData/Roaming/LegacyClonk is inconsistent and there is a consistent file in Program Files x86, the file in Program Files x86 will still be ignored and the program will throw the error which is already given to the user now if a c4-file cannot be processed. Here it is up to the user to remove or fix the faulty file as it's already the case today.

Ad 5: This prevents a user from accidentally copying vanilla packages into AppData/Roaming/LegacyClonk (or saving modified vanilla packages from other hosts) which are then no longer updated. If the advanced user wants to change a vanilla file on purpose, he can rename the original vanilla file and move his modified file to the place where it was in Program Files x86. The advanced user can be expected to handle a file system and admin rights.

Independently of this we could consider moving LegacyClonk to AppData/Local to also run the updater without admin rights. But here you would not have a system-wide installation anymore, the double check, if files are present in the Clonk folder (4. and 5.) would be dropped, because there is no reason to store non-Vanilla packages in AppData/Local anymore. Under Program Files x86 there is the reason that the advanced user might want to make a certain package available to several Windows users. AppData/Local would be in the user directory.

**Comment by Somebodyisnobody** [comment]
Memo: Saving a modified Objects.c4d or an other vanilla package would be useless as the original packet would be prioritized.

**Comment by maxmitti** [comment]
Closed in favor of #36.
