### ISSUE TITLE
CursorXXXXXLarge: File not found or invalid on Macos

### ISSUE THREAD

**Issue by rene-dev** [legacyclonk/LegacyClonk#26]
Hi, Im running into the following issue after compiling and copying all c4f and c4g files:

[02:05:28] Command line: 
[02:05:28] ""
[02:05:28] LegacyClonk 
[02:05:28] Version: 4.9.10.9 [341]  mac
[02:05:28]   Using OpenGL...
[02:05:28] No Gamepad found
[02:05:28] LegacyClonk is a fan project based on Clonk Rage.
[02:05:28] 'Clonk' is a registered trademark of Matthes Bender.
[02:05:28] Loading graphics...
[02:05:28] Error at graphics file CursorXXXXXLarge: File not found or invalid
[02:05:28] Game cleared.
[02:05:28] Engine shut down.

Im running 10.15.4 and 62eb647dafcc9d02c2939d81017afc8ed31538e3

**Comment by rene-dev** [comment]
looks like c4g and c4f files from the linux version are broken, the windows files work.

**Comment by maxmitti** [comment]
What Linux version are you talking about?
I just checked the files and that cursor graphic seems fine.

**Comment by rene-dev** [comment]
I downloaded the linux version form clonk.de, and the cursor files were missing:
rene@renes-iMac build % ./c4group Graphics.c4g | grep -i cursor
          CursorSmall.png    12637 Bytes 21.01.11 10:34:24 !46487876 
         CursorMedium.png    25864 Bytes 21.01.11 10:34:24 !B84FFFE8 
          CursorLarge.png    35569 Bytes 21.01.11 10:34:24 !1889B89E 
rene@renes-iMac build %

the files form the windows version are ok:

rene@renes-iMac build % ./c4group Graphics.c4g | grep -i cursor
          CursorSmall.png    12637 Bytes 18.04.20 19:22:07 !46487876 
         CursorMedium.png    25864 Bytes 18.04.20 19:22:07 !B84FFFE8 
          CursorLarge.png    35569 Bytes 18.04.20 19:22:07 !1889B89E 
         CursorXLarge.png    53078 Bytes 18.04.20 19:22:07 !622E2362 
        CursorXXLarge.png    76274 Bytes 18.04.20 19:22:07 !11272831 
       CursorXXXLarge.png   127102 Bytes 18.04.20 19:22:07 !DB79D6C5 
      CursorXXXXLarge.png   236469 Bytes 18.04.20 19:22:07 !17CC29A1 
     CursorXXXXXLarge.png   408856 Bytes 18.04.20 19:22:07 !ED6ABD4D 
rene@renes-iMac build %

**Comment by maxmitti** [comment]
Ok. LC needs it's own Graphics.c4g and System.c4g and also has other updated content.
The current [System.c4g](https://github.com/legacyclonk/LegacyClonk/releases/download/continuous-v340/System.c4g) and [Graphics.c4g](https://github.com/legacyclonk/LegacyClonk/releases/download/continuous-v340/Graphics.c4g) can be downloaded from the Github Release.

All current content can be downloaded [here](https://update.clonkspot.org/lc/lc_49109.zip).
