### ISSUE TITLE
String IDS_ERR_DDRAW fehlerhaft

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#3]
The string IDS_ERR_DDRAW is obsolete.
https://github.com/legacyclonk/LegacyClonk/blob/5bd069adbea57361ea88420e156b8af976d44bda/planet/System.c4g/LanguageDE.txt#L571
https://github.com/legacyclonk/LegacyClonk/blob/5bd069adbea57361ea88420e156b8af976d44bda/planet/System.c4g/LanguageUS.txt#L572
https://github.com/legacyclonk/LegacyClonk/blob/f7ae85e666fb552758c86199b2500371f050fbed/src/C4Application.cpp#L188-L190

I propose to rename the string to "IDS_ERR_OPENGL", audjusting the message and the functions.
`IDS_ERR_OPENGL=Failure while initalizing OpenGL.`
`IDS_ERR_OPENGL=Fehler bei der Initialisierung von OpenGL`

**Comment by Fulgen301** [comment]
`IDS_ERR_DDRAW` indicates an error in `DDrawInit`, so its identifier should not be changed - though the error message is obsolete, I agree.
