### ISSUE TITLE
Confusing behavior with "(Ctrl|Shift) + Enter"

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#38]
We have following behaviour in v345:
| Key | Chat status | Behavior |
| ------------- | ------------- | ------------- |
| Ctrl + Enter | Chat closed  | Opens chat with (") |
| Ctrl + Enter | Chat opened, empty | Does nothing |
| Ctrl + Enter | Chat opened, filled | Does nothing |
| Shift + Enter | Chat closed  | Opens chat with (/team ) |
| Shift + Enter | Chat opened, empty | Overwrites chat with (/team ) |
| Shift + Enter | Chat opened, filled | Overwrites chat with (/team ) | 

I suggest following:
| Key | Chat status | Behavior |
| ------------- | ------------- | ------------- |
| Ctrl + Enter | Chat closed  | Opens chat with (") |
| Ctrl + Enter | Chat opened, empty | Overwrites chat with (") |
| Ctrl + Enter | Chat opened, filled | Does nothing |
| Shift + Enter | Chat closed  | Opens chat with (/team ) |
| Shift + Enter | Chat opened, empty | Overwrites chat with (/team ) |
| Shift + Enter | Chat opened, filled | Does nothing |

**Comment by Somebodyisnobody** [comment]
For the protocol:
- 51368659338f6b2bc79605dfa6a88d466148f7dc
- We discussed about a dropdown-toggle left hand of the text field which has the three options
  - Team
  - Clonk
  - All.

  The options would be toogled by mouse or pressing a special key while the chat window is opened. This would eliminate co-existing combinations "(CTRL|SHIFT) + Enter". We didn't found a key which would fit for this job.

**Comment by Fulgen301** [comment]
As the original behaviour has been fixed in v346, I'm going to close this for now.
