### ISSUE TITLE
Select number of teams for random teams

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#39]
When calculating random teams the host should have the possibility to set the number of teams. At the moment the players are distributed over all available teams.

**Comment by maxmitti** [comment]
Good point. I wonder, if scenarios should also have more control over this.

**Comment by Fulgen301** [comment]
Indeed they should - a good example is CMC's team configuration in the chooser which isn't able to create or destroy teams which, however, is quite useful for ingame team configuration as the teams do depend on the chosen goal to a degree.

**Comment by maxmitti** [comment]
Ok, but I meant specifically random team settings and how many teams are used.

**Comment by Somebodyisnobody** [comment]
I find the end screen so bleak when the windmill stops moving, the fire freezes or the helicopter stops crashing into the mountain. That's what it's all about for me. I don't think it has a negative impact if the game continues. If it's won or lost, the helicopter can kiss the mountain, it doesn't matter. But maybe running clonks should stop in order not to drown, etc.
But otherwise I don't see any disadvantages.

**Comment by Fulgen301** [comment]
Wrong issue.

**Comment by maxmitti** [comment]
Why wrong issue?

**Comment by maxmitti** [comment]
Done.
![Done](https://i.imgur.com/p1IdaZZ.png)

**Comment by Somebodyisnobody** [comment]
😍
Can I ask what "automatic" does?

**Comment by maxmitti** [comment]
https://github.com/legacyclonk/LegacyClonk/commit/7f2d3822d725c80ffe6becb7a44cff2cf76d0ae6#diff-98b94abc519899bf5042e8c07366a9e70ca92812e1df4a7df7dd607bab87f2e4R975

Basically it is the old behavior.
