### ISSUE TITLE
Free view moves strangely if the game is paused

### ISSUE THREAD

**Issue by bratkartoff** [legacyclonk/LegacyClonk#40]
Start a record (of a large scenario)
pause the game
press the left arrow key -> the camera moves to the left
press the right arrow key -> the camera continues to move to the left, then slows down and moves to the right
the up and down keys move the camera diagonally

**Comment by Cyprex** [comment]
Being a spectator seems to have the same issue(to become a spectator start a scenario, surrender from context menu and hit continue playing)
Input seems to "lag" a bit(previous input is used instead of/in addition to the key you actually pressed), from Discord: 
> Ist sehr interessant wenn ich L R L R L R(abwechselnd Linke und rechte pfeiltaste) Drücke wird jeder zweite input ignoriert,  entweder alle rechts oder alle links je nachdem wie man anfängt. Aber L L L L scrollt mit jedem tastendruck. L L L L R R R R R R R R Scrollt irgendwann nach rechts aber die ersten paar R Tastendrücke bewegen die Kamera nach links
