### ISSUE TITLE
Register clonk:// protocol with updater

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#45]
Most users don't run LC as admin but that's needed to set `HKEY_CLASSES_ROOT\clonk\*`. I suggest to let the updater set the protocol as it runs as always admin. Another option would be to ask the user at startup, if he want to restart LC as admin to register the clonk protocol.

**Comment by Fulgen301** [comment]
According to https://stackoverflow.com/a/29528040, admin rights aren't even mandatory for per-user protocols, which is the better solution in my opinion.

**Comment by Somebodyisnobody** [comment]
is this possible before 346? 🙏

**Comment by Fulgen301** [comment]
How can an update be possible without an update? As a separate tool, maybe.

Somebodyisnobody <notifications@github.com> schrieb am Mo., 25. Jän. 2021,
00:00:

**Comment by Somebodyisnobody** [comment]
*with

Am 25.01.2021 um 01:16 schrieb Fulgen301:

**Comment by Fulgen301** [comment]
Implemented in ae1d61bbb16611f4a8e3e2c50e699f896e003d5e.
