### ISSUE TITLE
implement verbose mode

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#5]
Clonk has problems with loading the log when

- Client is being kicked
- Host leaves the lobby
- Connection error in lobby
- ecetera

At the moment, each network packed is being logged and written on drive. In >99% of cases you don't need such a detailled log. The log reaches sizes up to 350k bytes per minute. (Field test: 1 Client with 2 active players on DerServer). Besides the loading problems, the data is constantly written to the HDD/SSD but that's just by the way.

I propose to exclude the network packages from the clonk.log and implement a --verbose argument to enable logging of network packages.

**Comment by maxmitti** [comment]
The network packet dump has been disabled in a7cab20ca6b9748f42ea39a2a3eccabfc8f87b02, but without a verbose option.
Instead, interested people have to compile their own engine with enabled dumping.
