### ISSUE TITLE
Use Windows built-in dump generator when LC crashes

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#52]
While a registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\clonk.exe` DWORD `DumpType` = 1 is set, Windows creates a crash dump in `%localappdata%\CrashDumps\`.
Documentation: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Suggestion:

1. Set the registry value to 1 with c4group-update when it's running as admin (activate crash dumps by windows)
2. Rebuild the Structured Exception Handler in LC to not create own crashdumps in `...\AppData\Roaming\LegacyClonk\` and change the crash message pointing to `%localappdata%\CrashDumps\`.

**Comment by Fulgen301** [comment]
This would need LC to mess with global system settings, and the builtin crash handler can be more flexible.
