### ISSUE TITLE
Loop music restarts with delay and a new log message

### ISSUE THREAD

**Issue by Fulgen301** [legacyclonk/LegacyClonk#55]
Looping music does not loop continuously any more, instead, it restarts after a short delay and also logs a log message displaying the music title, effectively behaving like play a new music track which happens to be the same one.

**Comment by maxmitti** [comment]
Does it happen with every audio system implementation?

**Comment by maxmitti** [comment]
Nevermind. The I found the issue in C4MusicSystem already. I am just working on the solution now.
