### ISSUE TITLE
Chatname not displayed in teamchat when chatname surrounded braces

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#58]
Like shown here a player with a chatname surrounded with braces. If he writes something in the teamchat the sending client converts `/team foo` in `{playername} foo`. This is sent to other participants in the game. When the chatname is surrounded by braces for example a player with the chatname `{bar}`, a team-scoped message results in `{{bar}} foo`. This in turn is interpreted as an instruction to interpret the content in the braces as a DefCore ID and to display the corresponding symbol of this ID. For example `{{BIRD}}` results in a [bird from Objects.c4d](https://github.com/legacyclonk/content/blob/master/Objects.c4d/Animals.c4d/Bird.c4d/Graphics.png).
![grafik](https://user-images.githubusercontent.com/35230554/128597523-66c3efda-dc21-47c1-a081-0e160d19443d.png)

The bug results from the semantic mixing of several pieces of information in the message. The message should keep this information separate in a standardised format and not send it loosely through world's history as a string. This means that the metadata such as transmission time, name of the sender, type of message (teamchat, normalchat, zitatchat or command) as well as the payload should be sent in individual attributes of an object. This is the only way to avoid problems like this.

**Comment by Somebodyisnobody** [comment]
Now first the braces are removed BEFORE determining in which scope and layout the message is displayed. This is simply poorly solved. First images have to be parsed of the strings, then the name has to be put into braces becasue it's a teammessage and at the very end the name is inserted as string.

**Comment by Fulgen301** [comment]
> Now first the braces are removed BEFORE determining in which scope and layout the message is displayed.

Incorrect, they are removed upon validating `VAL_NameNoEmpty` and `VAL_NameAllowEmpty`, which are the validation types used for client, nick and player names and nothing else.

> This is simply poorly solved. First images have to be parsed of the strings, then the name has to be put into braces becasue it's a teammessage and at the very end the name is inserted as string.

This is solved without implementing special cases into the text rendering routine and fixes the bug in question. Should the rendering be changed? Yes. Is it in scope of this issue? Definitely not.

> And in two weeks we find out that "%" doesn't work either or something....

I doubt user input is passed to `printf`...
