### ISSUE TITLE
Disabling TCP or UDP causes using of port 65535 (2 bytes max)

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/LegacyClonk#59]
When the user disable one protocol in the game options the port 65535 is used. When both protocols are disabled error "no protocols availabe" is thrown.
![grafik](https://user-images.githubusercontent.com/35230554/128598223-010ad32f-8ff4-4a1c-a2e7-35cf3d4ef4da.png)

I expect a protocol to be disabled when I set it disabled.

**Comment by maxmitti** [comment]
Should be fixed by 164126bd076dbed8464314a517a2c2ddf1972cad.

**Comment by Somebodyisnobody** [comment]
@jan5 can you close it after testing?

**Comment by maxmitti** [comment]
Tested and works.
