### ISSUE TITLE
Scenarios in ModernCombat.c4f/Classic.c4f don't load correctly in Singleplayer

### ISSUE THREAD

**Issue by bratkartoff** [legacyclonk/LegacyClonk#74]
Starting Broadcast Station via the "Start Game" menu gives me this:

![2022-02-26_12:21:17](https://user-images.githubusercontent.com/46403888/155841297-c49feb8e-98f9-49d6-9d2b-1d354dbec685.png)

Tested so far:
```
ModernCombat.c4f/Classic.c4f/CMC_OperationMetro.c4s
ModernCombat.c4f/Classic.c4f/CMC_BroadcastStation.c4s
ModernCombat.c4f/Classic.c4f/CMC_SiegeOfControl.c4s
```
are broken, and
```
ModernCombat.c4f/CMC_Oasis.c4s
ModernCombat.c4f/CMC_IslandStrike.c4s
```
work fine.

The Classic.c4f-scenarios also work fine if they are started via network mode.

Versions: 349 and 351 (Linux)

**Comment by maxmitti** [comment]
Thanks for the detailed analysis.
It seems to be a problem when not using preloading, as it also happens when in network mode with disabled preloading.

**Comment by maxmitti** [comment]
Turns out that due to the changes introduced for preloading we discovered a bug in the C4Group implementation regarding nested groups.
