### ISSUE TITLE
Gamma not working for some people

### ISSUE THREAD

**Issue by Fulgen301** [legacyclonk/LegacyClonk#77]
Some people have reported that they don't experience any Gamma effects despite having it enabled and using [non-HDR screens](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-setdevicegammaramp).

**Comment by Somebodyisnobody** [comment]
![grafik](https://user-images.githubusercontent.com/35230554/156899838-0edbfeb5-38cc-4b62-893c-33030e571a29.png)
@OffizierMichael why can't you get yourself to post here? If Fulgen also does this with your mindset when fixing the problem then good night....

**Comment by Somebodyisnobody** [comment]
Danghor:
Windows 10 Pro
Nvidia GeForce GTX 1070 (MSI)

**Comment by Fulgen301** [comment]
It will now log an error to `Clonk.log` should `SetGammaRamp` fail - further work on this issue is not planned since there are a number of reasons applying the gamma ramp may fail, it's a system wide screen correction after all.
