### ISSUE TITLE
AddMenuItem performance with Overlays

### ISSUE THREAD

**Issue by bratkartoff** [legacyclonk/LegacyClonk#80]
While ce127c265c4a3b56f397ace9792e1ed539adfebf fixed the performance of `AddMenuItem` in some cases, the performance is still bad when using `iExtra = C4MN_Add_ImgObject` with an Object that has an Overlay.

### Test case: A rock that slows down the game if you collect it
This code has a noticable performance hit on my machine. While the FPS counter constantly shows 36, the clonks definitely walk slower (I'd say around 25-30 fps).

It's even more noticable with `/fast`:
- `/fast 3` without the menu: 180 fps
- `/fast 3` with menu shown: 45 fps 
#### Script.c
```scala
#strict 3

public func Timer()
{
  var clonk = Contained();
  if(!clonk) return;

  if(GetMenu(clonk))
    ClearMenuItems(clonk);
  else
    CreateMenu(ROCK,clonk,nil,C4MN_Extra_Info,"a menu",0,C4MN_Style_Dialog);

  for(var i = 0; i < 6; i++)
  {
    AddMenuItem(Format("Rock %v",i),"",GetID(),clonk,100,nil,"info",C4MN_Add_ImgObject,this);
  }
}

public func Initialize()
{
  SetGraphics("OVERLAY", nil, GetID(), 1, GFXOV_MODE_Picture);
}
```

#### DefCore
```ini
TimerCall=Timer
Timer=1
```

**Comment by maxmitti** [comment]
Yes, that’s true, but it can’t really be fixed in a reasonable way without major changes.
It also has to be guaranteed that it still works when the object is being deleted after calling AddMenuItem, so a simple object reference does not help.

**Comment by bratkartoff** [comment]
Is it possible to fix the performance of `C4MN_Add_ImgIndexed`? In that case I could combine all possible overlays in `Graphics.png`

**Comment by maxmitti** [comment]
Yes, that is reasonable to optimize.
But do you really need to refresh the menu in each frame?

In the past I also experienced performance issues with constantly refreshing menus.
Most of the time it makes much more sense to just update the menus when something changed.

**Comment by bratkartoff** [comment]
It's the FlagChooser menu for CMC, it shows the capture percentage next to the flag (and changes the overlay if the flag is being captured).
Since the capture percentage updates every frame, the number shown in the flag menu needs to update every frame as well, which as far as I known is only possible by updating the entire menu.

(In theory, it doesn't have to update every frame while no flag is being captured, but since in that case it only shows default icons without an overlay that doesn't cause a performance issue).
