### ISSUE TITLE
Scale does not apply to all Views

### ISSUE THREAD

**Issue by ChemoCosmo** [legacyclonk/LegacyClonk#87]
When using the Scale attribute, DefCore-attributes regarding Picture etc. are expected to reflect the actual objects size, not the actual image size(?) This works well for the Clonks inventory-view in the bottom left corner.

However, it does not work with the container-view-, research-view- and buy-menu-view-depiction. It also does not work with the In-Editor-Preview.

So Scale=200 with a 64x64px image will display a Picture=0,0,32,32 correctly for the inventory view but not the research- container- or build-view. Picure=0,0,64,64 works vice versa. So there is no way to make it work for all depictions at once.

(Also, only Picure=0,0,64,64 works for the In-Editor-Preview.)

See the Bouy in this Test scenario: https://we.tl/t-2dgDvw3XV9

**Comment by maxmitti** [comment]
LC does not have Editor.exe, you are probably using the one from Clonk Rage.
Consequently it wont be fixed there.
