### ISSUE TITLE
Scale not respected by Message-Function

### ISSUE THREAD

**Issue by ChemoCosmo** [legacyclonk/LegacyClonk#94]
The _Message_-Function seems not be able to handle the scale attribute correctly.

How to reproduce:

- Start a scenario with the activated seastar pack from the attachement, including an object with 200% scaled graphics. It's Defcore also has a Picture entry with adjusted values (50% of actual pixels).

- `Message("{{WIPF}}")` correctly shows a wipf icon, since Wipf object is not scaled.

- `Message("{{FM5P}}")` however shows a wrong picture of the sea star, since it has a scale factor in the DefCore.

Note that the scale factor is correctly displayed by the clonks inventory.

Also, _Message_-function does not consider Title.png images.

[Seastar.zip](https://github.com/legacyclonk/LegacyClonk/files/10147741/Seastar.zip)

[edit] Fixed typo in Defcore

**Comment by maxmitti** [comment]
Thanks, I will look into the message problem.

But I think you got confused about `Title.png`.
It is only used in Editor.exe and for Scenarios and Folders (c4s, c4f) in the scenario selection menu.
I think `Picture.png` is the one that should override `Picture` from `DefCore.txt`.

**Comment by ChemoCosmo** [comment]
Ahh, i see, However, _Message_ function also ignores Picture.png.

**Comment by maxmitti** [comment]
Sorry, I was mistaken. Picture.png doesn’t seem to do anything ingame in general.
So at least Message is consistent in that regard.
